"""
AI Agent Security Monitoring Framework

Provides comprehensive monitoring and logging for AI agent operations
to detect suspicious behavior and security violations.
"""

import hashlib
import json
import logging
import re
import time
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional

# Configure logging
logger = logging.getLogger(__name__)


class SecurityEventType(Enum):
    """Types of security events that can be logged."""

    INPUT_VALIDATION_FAILURE = "input_validation_failure"
    OUTPUT_SCAN_VIOLATION = "output_scan_violation"
    ACCESS_DENIED = "access_denied"
    SUSPICIOUS_BEHAVIOR = "suspicious_behavior"
    API_ABUSE = "api_abuse"
    RATE_LIMIT_EXCEEDED = "rate_limit_exceeded"
    UNAUTHORIZED_ACCESS = "unauthorized_access"
    DATA_EXFILTRATION_ATTEMPT = "data_exfiltration_attempt"
    MALICIOUS_CODE_GENERATION = "malicious_code_generation"
    SECURITY_BYPASS_ATTEMPT = "security_bypass_attempt"


class SecuritySeverity(Enum):
    """Security event severity levels."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"

    def __lt__(self, other):
        if self.__class__ is other.__class__:
            order = {"low": 1, "medium": 2, "high": 3, "critical": 4}
            return order[self.value] < order[other.value]
        return NotImplemented

    def __le__(self, other):
        if self.__class__ is other.__class__:
            order = {"low": 1, "medium": 2, "high": 3, "critical": 4}
            return order[self.value] <= order[other.value]
        return NotImplemented

    def __gt__(self, other):
        if self.__class__ is other.__class__:
            order = {"low": 1, "medium": 2, "high": 3, "critical": 4}
            return order[self.value] > order[other.value]
        return NotImplemented

    def __ge__(self, other):
        if self.__class__ is other.__class__:
            order = {"low": 1, "medium": 2, "high": 3, "critical": 4}
            return order[self.value] >= order[other.value]
        return NotImplemented


class AIAgentSecurityMonitor:
    """
    Monitors AI agent operations for security violations and suspicious behavior.

    This class provides comprehensive security monitoring including:
    - Operation logging and audit trails
    - Suspicious behavior detection
    - Rate limiting and abuse prevention
    - Security violation tracking
    - Alert generation for critical events
    """

    def __init__(self, log_directory: str = "logs/security"):
        self.log_directory = Path(log_directory)
        self.log_directory.mkdir(parents=True, exist_ok=True)

        # Security log files
        self.audit_log = self.log_directory / "ai_agent_audit.log"
        self.security_events_log = self.log_directory / "security_events.log"
        self.metrics_log = self.log_directory / "security_metrics.json"

        # Rate limiting tracking
        self.rate_limits: Dict[str, List[float]] = {}

        # Suspicious patterns
        self.suspicious_patterns = [
            r"rm\s+-rf\s+/",
            r"DROP\s+TABLE",
            r"DELETE\s+FROM.*WHERE.*=.*",
            r"sudo\s+",
            r"curl.*\|.*sh",
            r"wget.*\|.*sh",
            r"eval\s*\(",
            r"exec\s*\(",
            r"__import__\s*\(",
            r"subprocess\.",
            r"os\.system",
            r"os\.popen",
        ]

        # API key patterns (for detecting leaks)
        self.secret_patterns = [
            r"sk-[a-zA-Z0-9]{48}",  # OpenAI API keys
            r"ghp_[a-zA-Z0-9]{36}",  # GitHub tokens
            r"AKIA[0-9A-Z]{16}",  # AWS access keys
            r"ya29\.[0-9A-Za-z\-_]+",  # Google OAuth
            r"xox[baprs]-[0-9a-zA-Z-]{10,48}",  # Slack tokens
        ]

        # Initialize metrics
        self.metrics = {
            "total_operations": 0,
            "security_violations": 0,
            "blocked_operations": 0,
            "suspicious_activities": 0,
            "last_updated": datetime.utcnow().isoformat(),
        }

        logger.info(
            f"AI Agent Security Monitor initialized - logs: {self.log_directory}"
        )

    def log_agent_operation(
        self,
        agent_id: str,
        operation_type: str,
        input_data: str,
        output_data: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> str:
        """
        Log an AI agent operation for audit trail.

        Args:
            agent_id: Unique identifier for the AI agent
            operation_type: Type of operation (code_generation, file_modification, etc.)
            input_data: Input provided to the agent
            output_data: Output generated by the agent
            metadata: Additional metadata about the operation

        Returns:
            operation_id: Unique identifier for this operation
        """
        operation_id = self._generate_operation_id(agent_id, operation_type)
        timestamp = datetime.utcnow().isoformat()

        # Create audit record
        audit_record = {
            "operation_id": operation_id,
            "timestamp": timestamp,
            "agent_id": agent_id,
            "operation_type": operation_type,
            "input_data": input_data,
            "output_data": output_data,
            "input_hash": self._hash_content(input_data),
            "output_hash": self._hash_content(output_data) if output_data else None,
            "metadata": metadata or {},
            "input_length": len(input_data),
            "output_length": len(output_data) if output_data else 0,
        }

        # Write to audit log
        with open(self.audit_log, "a") as f:
            f.write(json.dumps(audit_record) + "\n")

        # Also write to agent operations JSONL file for easy querying
        operations_jsonl = (
            self.log_directory
            / f"agent_operations_{datetime.utcnow().strftime('%Y%m%d')}.jsonl"
        )
        with open(operations_jsonl, "a") as f:
            f.write(json.dumps(audit_record) + "\n")

        # Update metrics
        self.metrics["total_operations"] += 1
        self._update_metrics()

        logger.debug(f"Logged operation {operation_id} for agent {agent_id}")
        return operation_id

    def check_input_security(
        self, agent_id: str, input_data: str, operation_type: str
    ) -> Dict[str, Any]:
        """
        Check input data for security issues.

        Args:
            agent_id: Agent identifier
            input_data: Input data to check
            operation_type: Type of operation

        Returns:
            Security check results
        """
        violations = []
        severity = SecuritySeverity.LOW

        # Check for suspicious patterns
        for pattern in self.suspicious_patterns:
            if re.search(pattern, input_data, re.IGNORECASE):
                violations.append(
                    {
                        "type": "suspicious_pattern",
                        "pattern": pattern,
                        "description": f"Potentially dangerous pattern detected: {pattern}",
                    }
                )
                severity = SecuritySeverity.HIGH

        # Check for secrets in input
        for pattern in self.secret_patterns:
            if re.search(pattern, input_data):
                violations.append(
                    {
                        "type": "secret_detected",
                        "pattern": pattern,
                        "description": "Potential API key or secret detected in input",
                    }
                )
                severity = SecuritySeverity.CRITICAL

        # Check rate limits
        if self._is_rate_limited(agent_id, operation_type):
            violations.append(
                {
                    "type": "rate_limit_exceeded",
                    "description": f"Rate limit exceeded for {operation_type}",
                }
            )
            severity = SecuritySeverity.MEDIUM

        # Log violations if any
        if violations:
            self.log_security_event(
                SecurityEventType.INPUT_VALIDATION_FAILURE,
                agent_id,
                f"Input security violations detected for {operation_type}",
                severity,
                {
                    "violations": violations,
                    "input_hash": self._hash_content(input_data),
                },
            )

        return {
            "is_safe": len(violations) == 0,
            "violations": violations,
            "severity": severity.value,
            "action": (
                "block"
                if severity in [SecuritySeverity.HIGH, SecuritySeverity.CRITICAL]
                else "warn" if len(violations) > 0 else "allow"
            ),
        }

    def check_output_security(
        self, agent_id: str, output_data: str, operation_type: str
    ) -> Dict[str, Any]:
        """
        Check output data for security issues.

        Args:
            agent_id: Agent identifier
            output_data: Output data to check
            operation_type: Type of operation

        Returns:
            Security check results
        """
        violations = []
        severity = SecuritySeverity.LOW

        # Check for secrets in output
        for pattern in self.secret_patterns:
            matches = re.finditer(pattern, output_data)
            for match in matches:
                violations.append(
                    {
                        "type": "secret_in_output",
                        "pattern": pattern,
                        "description": "AI agent generated output containing potential secret",
                        "redacted_match": match.group()[:10] + "***",
                    }
                )
                severity = SecuritySeverity.CRITICAL

        # Check for suspicious code patterns
        for pattern in self.suspicious_patterns:
            if re.search(pattern, output_data, re.IGNORECASE):
                violations.append(
                    {
                        "type": "suspicious_code",
                        "pattern": pattern,
                        "description": f"AI agent generated potentially dangerous code: {pattern}",
                    }
                )
                severity = max(severity, SecuritySeverity.HIGH)

        # Check for large data exfiltration
        if len(output_data) > 100000:  # 100KB threshold
            violations.append(
                {
                    "type": "large_output",
                    "size": len(output_data),
                    "description": "AI agent generated unusually large output (potential data exfiltration)",
                }
            )
            severity = max(severity, SecuritySeverity.MEDIUM)

        # Log violations if any
        if violations:
            self.log_security_event(
                SecurityEventType.OUTPUT_SCAN_VIOLATION,
                agent_id,
                f"Output security violations detected for {operation_type}",
                severity,
                {
                    "violations": violations,
                    "output_hash": self._hash_content(output_data),
                },
            )

        return {
            "is_safe": len(violations) == 0,
            "violations": violations,
            "severity": severity.value,
            "action": (
                "block"
                if severity == SecuritySeverity.CRITICAL
                else "warn" if len(violations) > 0 else "allow"
            ),
        }

    def log_security_event(
        self,
        event_type: SecurityEventType,
        agent_id: str,
        description: str,
        severity: SecuritySeverity = SecuritySeverity.MEDIUM,
        additional_data: Optional[Dict[str, Any]] = None,
    ) -> str:
        """
        Log a security event.

        Args:
            event_type: Type of security event
            agent_id: Agent that triggered the event
            description: Human-readable description
            severity: Event severity
            additional_data: Additional event data

        Returns:
            Event ID for this security event
        """
        # Generate unique event ID
        event_id = self._generate_operation_id(agent_id, f"security_{event_type.value}")
        timestamp = datetime.utcnow().isoformat()

        event_record = {
            "event_id": event_id,
            "timestamp": timestamp,
            "event_type": event_type.value,
            "agent_id": agent_id,
            "message": description,
            "severity": severity.value,
            "metadata": additional_data or {},
        }

        # Write to security events log (JSONL format for easy parsing)
        security_events_jsonl = (
            self.log_directory
            / f"security_events_{datetime.utcnow().strftime('%Y%m%d')}.jsonl"
        )
        with open(security_events_jsonl, "a") as f:
            f.write(json.dumps(event_record) + "\n")

        # Also write to the original log for backward compatibility
        with open(self.security_events_log, "a") as f:
            f.write(json.dumps(event_record) + "\n")

        # Update metrics
        self.metrics["security_violations"] += 1
        if severity in [SecuritySeverity.HIGH, SecuritySeverity.CRITICAL]:
            self.metrics["blocked_operations"] += 1
        self._update_metrics()

        # Log to application logger based on severity
        if severity == SecuritySeverity.CRITICAL:
            logger.critical(f"SECURITY ALERT: {description} (Agent: {agent_id})")
        elif severity == SecuritySeverity.HIGH:
            logger.error(f"Security violation: {description} (Agent: {agent_id})")
        elif severity == SecuritySeverity.MEDIUM:
            logger.warning(f"Security concern: {description} (Agent: {agent_id})")
        else:
            logger.info(f"Security event: {description} (Agent: {agent_id})")

        return event_id

    def get_agent_metrics(self, agent_id: str) -> Dict[str, Any]:
        """
        Get security metrics for a specific agent.

        Args:
            agent_id: Agent identifier

        Returns:
            Agent security metrics
        """
        # Read recent audit logs for this agent
        agent_operations = []
        security_events = []

        try:
            # Parse audit log
            if self.audit_log.exists():
                with open(self.audit_log, "r") as f:
                    for line in f:
                        try:
                            record = json.loads(line.strip())
                            if record.get("agent_id") == agent_id:
                                agent_operations.append(record)
                        except json.JSONDecodeError:
                            continue

            # Parse security events log
            if self.security_events_log.exists():
                with open(self.security_events_log, "r") as f:
                    for line in f:
                        try:
                            record = json.loads(line.strip())
                            if record.get("agent_id") == agent_id:
                                security_events.append(record)
                        except json.JSONDecodeError:
                            continue

        except Exception as e:
            logger.error(f"Error reading logs for agent metrics: {e}")

        # Calculate metrics
        total_operations = len(agent_operations)
        total_violations = len(security_events)
        critical_events = len(
            [e for e in security_events if e.get("severity") == "critical"]
        )
        high_events = len([e for e in security_events if e.get("severity") == "high"])

        return {
            "agent_id": agent_id,
            "total_operations": total_operations,
            "total_violations": total_violations,
            "critical_events": critical_events,
            "high_events": high_events,
            "violation_rate": total_violations / max(total_operations, 1),
            "last_operation": (
                agent_operations[-1]["timestamp"] if agent_operations else None
            ),
            "last_violation": (
                security_events[-1]["timestamp"] if security_events else None
            ),
        }

    def generate_security_report(self) -> Dict[str, Any]:
        """
        Generate a comprehensive security report.

        Returns:
            Security report data
        """
        report_timestamp = datetime.utcnow().isoformat()

        # Overall metrics
        overall_metrics = self.metrics.copy()

        # Recent security events (last 24 hours)
        recent_events = self._get_recent_events(hours=24)

        # Agent-specific metrics
        agent_metrics = {}
        for event in recent_events:
            agent_id = event.get("agent_id", "unknown")
            if agent_id not in agent_metrics:
                agent_metrics[agent_id] = self.get_agent_metrics(agent_id)

        return {
            "report_timestamp": report_timestamp,
            "overall_metrics": overall_metrics,
            "recent_events_24h": len(recent_events),
            "agent_metrics": agent_metrics,
            "top_security_concerns": self._analyze_top_concerns(recent_events),
            "recommendations": self._generate_recommendations(
                recent_events, agent_metrics
            ),
        }

    def _generate_operation_id(self, agent_id: str, operation_type: str) -> str:
        """Generate unique operation ID."""
        timestamp = str(time.time())
        content = f"{agent_id}:{operation_type}:{timestamp}"
        return hashlib.sha256(content.encode()).hexdigest()[:16]

    def _hash_content(self, content: str) -> str:
        """Generate hash of content for logging."""
        if not content:
            return ""
        return hashlib.sha256(content.encode()).hexdigest()[:16]

    def _is_rate_limited(self, agent_id: str, operation_type: str) -> bool:
        """Check if agent is rate limited for operation type."""
        key = f"{agent_id}:{operation_type}"
        current_time = time.time()
        window_minutes = 10
        max_operations = 100  # Max 100 operations per 10 minutes

        # Initialize or clean old entries
        if key not in self.rate_limits:
            self.rate_limits[key] = []

        # Remove old entries outside window
        self.rate_limits[key] = [
            t for t in self.rate_limits[key] if current_time - t < (window_minutes * 60)
        ]

        # Check limit
        if len(self.rate_limits[key]) >= max_operations:
            return True

        # Add current operation
        self.rate_limits[key].append(current_time)
        return False

    def _update_metrics(self) -> None:
        """Update metrics file."""
        self.metrics["last_updated"] = datetime.utcnow().isoformat()

        try:
            with open(self.metrics_log, "w") as f:
                json.dump(self.metrics, f, indent=2)
        except Exception as e:
            logger.error(f"Failed to update metrics: {e}")

    def _get_recent_events(self, hours: int = 24) -> List[Dict[str, Any]]:
        """Get recent security events."""
        cutoff_time = datetime.utcnow().timestamp() - (hours * 3600)
        recent_events = []

        try:
            if self.security_events_log.exists():
                with open(self.security_events_log, "r") as f:
                    for line in f:
                        try:
                            record = json.loads(line.strip())
                            event_time = datetime.fromisoformat(
                                record["timestamp"]
                            ).timestamp()
                            if event_time > cutoff_time:
                                recent_events.append(record)
                        except (json.JSONDecodeError, KeyError, ValueError):
                            continue
        except Exception as e:
            logger.error(f"Error reading recent events: {e}")

        return recent_events

    def _analyze_top_concerns(
        self, events: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """Analyze top security concerns from events."""
        concern_counts = {}

        for event in events:
            event_type = event.get("event_type", "unknown")
            severity = event.get("severity", "low")

            key = f"{event_type}:{severity}"
            if key not in concern_counts:
                concern_counts[key] = {
                    "count": 0,
                    "event_type": event_type,
                    "severity": severity,
                }
            concern_counts[key]["count"] += 1

        # Sort by severity and count
        severity_order = {"critical": 4, "high": 3, "medium": 2, "low": 1}
        top_concerns = sorted(
            concern_counts.values(),
            key=lambda x: (severity_order.get(x["severity"], 0), x["count"]),
            reverse=True,
        )[:5]

        return top_concerns

    def _generate_recommendations(
        self, recent_events: List[Dict[str, Any]], agent_metrics: Dict[str, Any]
    ) -> List[str]:
        """Generate security recommendations based on analysis."""
        recommendations = []

        # Check for high violation rates
        for agent_id, metrics in agent_metrics.items():
            if metrics["violation_rate"] > 0.1:  # 10% violation rate
                recommendations.append(
                    f"Agent {agent_id} has high violation rate ({metrics['violation_rate']:.1%}) - "
                    "consider additional input validation or retraining"
                )

        # Check for critical events
        critical_events = [e for e in recent_events if e.get("severity") == "critical"]
        if critical_events:
            recommendations.append(
                f"Found {len(critical_events)} critical security events in last 24h - "
                "immediate review recommended"
            )

        # Check for repeated patterns
        event_types = [e.get("event_type") for e in recent_events]
        if event_types.count("output_scan_violation") > 5:
            recommendations.append(
                "Multiple output scan violations detected - "
                "consider strengthening output validation rules"
            )

        if not recommendations:
            recommendations.append("No immediate security concerns detected")

        return recommendations

    def get_security_events(
        self,
        agent_id: Optional[str] = None,
        min_severity: Optional[SecuritySeverity] = None,
        event_type: Optional[SecurityEventType] = None,
        limit: Optional[int] = None,
    ) -> List[Dict[str, Any]]:
        """
        Get security events with optional filtering.

        Args:
            agent_id: Filter by agent ID
            min_severity: Filter by minimum severity level
            event_type: Filter by event type
            limit: Maximum number of events to return

        Returns:
            List of security events matching the filters
        """
        events = []
        seen_event_ids = set()

        try:
            # Read from both JSONL files and the main log
            event_files = list(self.log_directory.glob("security_events_*.jsonl"))
            if self.security_events_log.exists():
                event_files.append(self.security_events_log)

            for file_path in event_files:
                with open(file_path, "r") as f:
                    for line in f:
                        try:
                            event = json.loads(line.strip())

                            # Skip duplicates based on event_id
                            event_id = event.get("event_id")
                            if event_id and event_id in seen_event_ids:
                                continue
                            if event_id:
                                seen_event_ids.add(event_id)

                            # Apply filters
                            if agent_id and event.get("agent_id") != agent_id:
                                continue
                            if (
                                event_type
                                and event.get("event_type") != event_type.value
                            ):
                                continue
                            if min_severity:
                                event_severity = event.get("severity", "low")
                                severity_order = {
                                    "low": 1,
                                    "medium": 2,
                                    "high": 3,
                                    "critical": 4,
                                }
                                if severity_order.get(
                                    event_severity, 0
                                ) < severity_order.get(min_severity.value, 0):
                                    continue

                            events.append(event)
                        except json.JSONDecodeError:
                            continue
        except Exception as e:
            logger.error(f"Error reading security events: {e}")

        # Sort by timestamp (newest first)
        events.sort(key=lambda x: x.get("timestamp", ""), reverse=True)

        # Apply limit
        if limit:
            events = events[:limit]

        return events

    def get_agent_operations(
        self,
        agent_id: Optional[str] = None,
        operation_type: Optional[str] = None,
        limit: Optional[int] = None,
    ) -> List[Dict[str, Any]]:
        """
        Get agent operations with optional filtering.

        Args:
            agent_id: Filter by agent ID
            operation_type: Filter by operation type
            limit: Maximum number of operations to return

        Returns:
            List of operations matching the filters
        """
        operations = []
        seen_operation_ids = set()

        try:
            # Read from both JSONL files and the main audit log
            operation_files = list(self.log_directory.glob("agent_operations_*.jsonl"))
            if self.audit_log.exists():
                operation_files.append(self.audit_log)

            for file_path in operation_files:
                with open(file_path, "r") as f:
                    for line in f:
                        try:
                            operation = json.loads(line.strip())

                            # Skip duplicates based on operation_id
                            operation_id = operation.get("operation_id")
                            if operation_id and operation_id in seen_operation_ids:
                                continue
                            if operation_id:
                                seen_operation_ids.add(operation_id)

                            # Apply filters
                            if agent_id and operation.get("agent_id") != agent_id:
                                continue
                            if (
                                operation_type
                                and operation.get("operation_type") != operation_type
                            ):
                                continue

                            operations.append(operation)
                        except json.JSONDecodeError:
                            continue
        except Exception as e:
            logger.error(f"Error reading agent operations: {e}")

        # Sort by timestamp (newest first)
        operations.sort(key=lambda x: x.get("timestamp", ""), reverse=True)

        # Apply limit
        if limit:
            operations = operations[:limit]

        return operations

    def get_security_summary(self) -> Dict[str, Any]:
        """
        Get a summary of security events and statistics.

        Returns:
            Dictionary containing security summary statistics
        """
        all_events = self.get_security_events()

        # Count events by severity
        severity_counts = {"low": 0, "medium": 0, "high": 0, "critical": 0}
        for event in all_events:
            severity = event.get("severity", "low")
            if severity in severity_counts:
                severity_counts[severity] += 1

        # Count events by type
        type_counts = {}
        for event in all_events:
            event_type = event.get("event_type", "unknown")
            type_counts[event_type] = type_counts.get(event_type, 0) + 1

        # Get unique agents
        unique_agents = list(
            set(event.get("agent_id") for event in all_events if event.get("agent_id"))
        )

        return {
            "total_events": len(all_events),
            "events_by_severity": severity_counts,
            "events_by_type": type_counts,
            "agents_monitored": unique_agents,  # List of agent IDs for membership checks
            "agent_count": len(unique_agents),  # Count of unique agents
            "summary_timestamp": datetime.utcnow().isoformat(),
        }

    def analyze_agent_behavior(self, agent_id: str) -> Dict[str, Any]:
        """
        Analyze behavior patterns for a specific agent.

        Args:
            agent_id: ID of the agent to analyze

        Returns:
            Dictionary containing behavior analysis results
        """
        # Get operations and security events for this agent
        operations = self.get_agent_operations(agent_id=agent_id)
        security_events = self.get_security_events(agent_id=agent_id)

        # Calculate risk score based on security events
        risk_score = 0
        severity_weights = {"low": 1, "medium": 3, "high": 7, "critical": 15}

        for event in security_events:
            severity = event.get("severity", "low")
            risk_score += severity_weights.get(severity, 1)

        # Generate recommendations based on analysis
        recommendations = []

        if len(security_events) > 10:
            recommendations.append(
                "High number of security events - consider additional monitoring"
            )

        critical_events = [
            e for e in security_events if e.get("severity") == "critical"
        ]
        if critical_events:
            recommendations.append(
                f"Found {len(critical_events)} critical security events - immediate review needed"
            )

        # Calculate violation rate
        violation_rate = len(security_events) / max(len(operations), 1)
        if violation_rate > 0.1:
            recommendations.append(
                f"High violation rate ({violation_rate:.1%}) - consider retraining"
            )

        if not recommendations:
            recommendations.append("No immediate security concerns detected")

        return {
            "agent_id": agent_id,
            "total_operations": len(operations),
            "security_events": len(security_events),
            "risk_score": risk_score,
            "violation_rate": violation_rate,
            "recommendations": recommendations,
            "analysis_timestamp": datetime.utcnow().isoformat(),
        }
