"""
AI Agent Security Monitoring Framework

Provides comprehensive monitoring and logging for AI agent operations
to detect suspicious behavior and security violations.
"""

import hashlib
import json
import logging
import re
import time
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional

# Configure logging
logger = logging.getLogger(__name__)


class SecurityEventType(Enum):
    """Types of security events that can be logged."""

    INPUT_VALIDATION_FAILURE = "input_validation_failure"
    OUTPUT_SCAN_VIOLATION = "output_scan_violation"
    ACCESS_DENIED = "access_denied"
    SUSPICIOUS_BEHAVIOR = "suspicious_behavior"
    API_ABUSE = "api_abuse"
    RATE_LIMIT_EXCEEDED = "rate_limit_exceeded"
    UNAUTHORIZED_ACCESS = "unauthorized_access"
    DATA_EXFILTRATION_ATTEMPT = "data_exfiltration_attempt"
    MALICIOUS_CODE_GENERATION = "malicious_code_generation"
    SECURITY_BYPASS_ATTEMPT = "security_bypass_attempt"


class SecuritySeverity(Enum):
    """Security event severity levels."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AIAgentSecurityMonitor:
    """
    Monitors AI agent operations for security violations and suspicious behavior.

    This class provides comprehensive security monitoring including:
    - Operation logging and audit trails
    - Suspicious behavior detection
    - Rate limiting and abuse prevention
    - Security violation tracking
    - Alert generation for critical events
    """

    def __init__(self, log_directory: str = "logs/security"):
        self.log_directory = Path(log_directory)
        self.log_directory.mkdir(parents=True, exist_ok=True)

        # Security log files
        self.audit_log = self.log_directory / "ai_agent_audit.log"
        self.security_events_log = self.log_directory / "security_events.log"
        self.metrics_log = self.log_directory / "security_metrics.json"

        # Rate limiting tracking
        self.rate_limits: Dict[str, List[float]] = {}

        # Suspicious patterns
        self.suspicious_patterns = [
            r"rm\s+-rf\s+/",
            r"DROP\s+TABLE",
            r"DELETE\s+FROM.*WHERE.*=.*",
            r"sudo\s+",
            r"curl.*\|.*sh",
            r"wget.*\|.*sh",
            r"eval\s*\(",
            r"exec\s*\(",
            r"__import__\s*\(",
            r"subprocess\.",
            r"os\.system",
            r"os\.popen",
        ]

        # API key patterns (for detecting leaks)
        self.secret_patterns = [
            r"sk-[a-zA-Z0-9]{48}",  # OpenAI API keys
            r"ghp_[a-zA-Z0-9]{36}",  # GitHub tokens
            r"AKIA[0-9A-Z]{16}",  # AWS access keys
            r"ya29\.[0-9A-Za-z\-_]+",  # Google OAuth
            r"xox[baprs]-[0-9a-zA-Z-]{10,48}",  # Slack tokens
        ]

        # Initialize metrics
        self.metrics = {
            "total_operations": 0,
            "security_violations": 0,
            "blocked_operations": 0,
            "suspicious_activities": 0,
            "last_updated": datetime.utcnow().isoformat(),
        }

        logger.info(
            f"AI Agent Security Monitor initialized - logs: {self.log_directory}"
        )

    def log_agent_operation(
        self,
        agent_id: str,
        operation_type: str,
        input_data: str,
        output_data: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> str:
        """
        Log an AI agent operation for audit trail.

        Args:
            agent_id: Unique identifier for the AI agent
            operation_type: Type of operation (code_generation, file_modification, etc.)
            input_data: Input provided to the agent
            output_data: Output generated by the agent
            metadata: Additional metadata about the operation

        Returns:
            operation_id: Unique identifier for this operation
        """
        operation_id = self._generate_operation_id(agent_id, operation_type)
        timestamp = datetime.utcnow().isoformat()

        # Create audit record
        audit_record = {
            "operation_id": operation_id,
            "timestamp": timestamp,
            "agent_id": agent_id,
            "operation_type": operation_type,
            "input_hash": self._hash_content(input_data),
            "output_hash": self._hash_content(output_data) if output_data else None,
            "metadata": metadata or {},
            "input_length": len(input_data),
            "output_length": len(output_data) if output_data else 0,
        }

        # Write to audit log
        with open(self.audit_log, "a") as f:
            f.write(json.dumps(audit_record) + "\n")

        # Update metrics
        self.metrics["total_operations"] += 1
        self._update_metrics()

        logger.debug(f"Logged operation {operation_id} for agent {agent_id}")
        return operation_id

    def check_input_security(
        self, agent_id: str, input_data: str, operation_type: str
    ) -> Dict[str, Any]:
        """
        Check input data for security issues.

        Args:
            agent_id: Agent identifier
            input_data: Input data to check
            operation_type: Type of operation

        Returns:
            Security check results
        """
        violations = []
        severity = SecuritySeverity.LOW

        # Check for suspicious patterns
        for pattern in self.suspicious_patterns:
            if re.search(pattern, input_data, re.IGNORECASE):
                violations.append(
                    {
                        "type": "suspicious_pattern",
                        "pattern": pattern,
                        "description": f"Potentially dangerous pattern detected: {pattern}",
                    }
                )
                severity = SecuritySeverity.HIGH

        # Check for secrets in input
        for pattern in self.secret_patterns:
            if re.search(pattern, input_data):
                violations.append(
                    {
                        "type": "secret_detected",
                        "pattern": pattern,
                        "description": "Potential API key or secret detected in input",
                    }
                )
                severity = SecuritySeverity.CRITICAL

        # Check rate limits
        if self._is_rate_limited(agent_id, operation_type):
            violations.append(
                {
                    "type": "rate_limit_exceeded",
                    "description": f"Rate limit exceeded for {operation_type}",
                }
            )
            severity = SecuritySeverity.MEDIUM

        # Log violations if any
        if violations:
            self.log_security_event(
                SecurityEventType.INPUT_VALIDATION_FAILURE,
                agent_id,
                f"Input security violations detected for {operation_type}",
                severity,
                {
                    "violations": violations,
                    "input_hash": self._hash_content(input_data),
                },
            )

        return {
            "is_safe": len(violations) == 0,
            "violations": violations,
            "severity": severity.value,
            "action": (
                "block"
                if severity in [SecuritySeverity.HIGH, SecuritySeverity.CRITICAL]
                else "allow"
            ),
        }

    def check_output_security(
        self, agent_id: str, output_data: str, operation_type: str
    ) -> Dict[str, Any]:
        """
        Check output data for security issues.

        Args:
            agent_id: Agent identifier
            output_data: Output data to check
            operation_type: Type of operation

        Returns:
            Security check results
        """
        violations = []
        severity = SecuritySeverity.LOW

        # Check for secrets in output
        for pattern in self.secret_patterns:
            matches = re.finditer(pattern, output_data)
            for match in matches:
                violations.append(
                    {
                        "type": "secret_in_output",
                        "pattern": pattern,
                        "description": "AI agent generated output containing potential secret",
                        "redacted_match": match.group()[:10] + "***",
                    }
                )
                severity = SecuritySeverity.CRITICAL

        # Check for suspicious code patterns
        for pattern in self.suspicious_patterns:
            if re.search(pattern, output_data, re.IGNORECASE):
                violations.append(
                    {
                        "type": "suspicious_code",
                        "pattern": pattern,
                        "description": f"AI agent generated potentially dangerous code: {pattern}",
                    }
                )
                severity = max(severity, SecuritySeverity.HIGH)

        # Check for large data exfiltration
        if len(output_data) > 100000:  # 100KB threshold
            violations.append(
                {
                    "type": "large_output",
                    "size": len(output_data),
                    "description": "AI agent generated unusually large output (potential data exfiltration)",
                }
            )
            severity = max(severity, SecuritySeverity.MEDIUM)

        # Log violations if any
        if violations:
            self.log_security_event(
                SecurityEventType.OUTPUT_SCAN_VIOLATION,
                agent_id,
                f"Output security violations detected for {operation_type}",
                severity,
                {
                    "violations": violations,
                    "output_hash": self._hash_content(output_data),
                },
            )

        return {
            "is_safe": len(violations) == 0,
            "violations": violations,
            "severity": severity.value,
            "action": "block" if severity == SecuritySeverity.CRITICAL else "warn",
        }

    def log_security_event(
        self,
        event_type: SecurityEventType,
        agent_id: str,
        description: str,
        severity: SecuritySeverity = SecuritySeverity.MEDIUM,
        additional_data: Optional[Dict[str, Any]] = None,
    ) -> None:
        """
        Log a security event.

        Args:
            event_type: Type of security event
            agent_id: Agent that triggered the event
            description: Human-readable description
            severity: Event severity
            additional_data: Additional event data
        """
        timestamp = datetime.utcnow().isoformat()

        event_record = {
            "timestamp": timestamp,
            "event_type": event_type.value,
            "agent_id": agent_id,
            "description": description,
            "severity": severity.value,
            "additional_data": additional_data or {},
        }

        # Write to security events log
        with open(self.security_events_log, "a") as f:
            f.write(json.dumps(event_record) + "\n")

        # Update metrics
        self.metrics["security_violations"] += 1
        if severity in [SecuritySeverity.HIGH, SecuritySeverity.CRITICAL]:
            self.metrics["blocked_operations"] += 1
        self._update_metrics()

        # Log to application logger based on severity
        if severity == SecuritySeverity.CRITICAL:
            logger.critical(f"SECURITY ALERT: {description} (Agent: {agent_id})")
        elif severity == SecuritySeverity.HIGH:
            logger.error(f"Security violation: {description} (Agent: {agent_id})")
        elif severity == SecuritySeverity.MEDIUM:
            logger.warning(f"Security concern: {description} (Agent: {agent_id})")
        else:
            logger.info(f"Security event: {description} (Agent: {agent_id})")

    def get_agent_metrics(self, agent_id: str) -> Dict[str, Any]:
        """
        Get security metrics for a specific agent.

        Args:
            agent_id: Agent identifier

        Returns:
            Agent security metrics
        """
        # Read recent audit logs for this agent
        agent_operations = []
        security_events = []

        try:
            # Parse audit log
            if self.audit_log.exists():
                with open(self.audit_log, "r") as f:
                    for line in f:
                        try:
                            record = json.loads(line.strip())
                            if record.get("agent_id") == agent_id:
                                agent_operations.append(record)
                        except json.JSONDecodeError:
                            continue

            # Parse security events log
            if self.security_events_log.exists():
                with open(self.security_events_log, "r") as f:
                    for line in f:
                        try:
                            record = json.loads(line.strip())
                            if record.get("agent_id") == agent_id:
                                security_events.append(record)
                        except json.JSONDecodeError:
                            continue

        except Exception as e:
            logger.error(f"Error reading logs for agent metrics: {e}")

        # Calculate metrics
        total_operations = len(agent_operations)
        total_violations = len(security_events)
        critical_events = len(
            [e for e in security_events if e.get("severity") == "critical"]
        )
        high_events = len([e for e in security_events if e.get("severity") == "high"])

        return {
            "agent_id": agent_id,
            "total_operations": total_operations,
            "total_violations": total_violations,
            "critical_events": critical_events,
            "high_events": high_events,
            "violation_rate": total_violations / max(total_operations, 1),
            "last_operation": (
                agent_operations[-1]["timestamp"] if agent_operations else None
            ),
            "last_violation": (
                security_events[-1]["timestamp"] if security_events else None
            ),
        }

    def generate_security_report(self) -> Dict[str, Any]:
        """
        Generate a comprehensive security report.

        Returns:
            Security report data
        """
        report_timestamp = datetime.utcnow().isoformat()

        # Overall metrics
        overall_metrics = self.metrics.copy()

        # Recent security events (last 24 hours)
        recent_events = self._get_recent_events(hours=24)

        # Agent-specific metrics
        agent_metrics = {}
        for event in recent_events:
            agent_id = event.get("agent_id", "unknown")
            if agent_id not in agent_metrics:
                agent_metrics[agent_id] = self.get_agent_metrics(agent_id)

        return {
            "report_timestamp": report_timestamp,
            "overall_metrics": overall_metrics,
            "recent_events_24h": len(recent_events),
            "agent_metrics": agent_metrics,
            "top_security_concerns": self._analyze_top_concerns(recent_events),
            "recommendations": self._generate_recommendations(
                recent_events, agent_metrics
            ),
        }

    def _generate_operation_id(self, agent_id: str, operation_type: str) -> str:
        """Generate unique operation ID."""
        timestamp = str(time.time())
        content = f"{agent_id}:{operation_type}:{timestamp}"
        return hashlib.sha256(content.encode()).hexdigest()[:16]

    def _hash_content(self, content: str) -> str:
        """Generate hash of content for logging."""
        if not content:
            return ""
        return hashlib.sha256(content.encode()).hexdigest()[:16]

    def _is_rate_limited(self, agent_id: str, operation_type: str) -> bool:
        """Check if agent is rate limited for operation type."""
        key = f"{agent_id}:{operation_type}"
        current_time = time.time()
        window_minutes = 10
        max_operations = 100  # Max 100 operations per 10 minutes

        # Initialize or clean old entries
        if key not in self.rate_limits:
            self.rate_limits[key] = []

        # Remove old entries outside window
        self.rate_limits[key] = [
            t for t in self.rate_limits[key] if current_time - t < (window_minutes * 60)
        ]

        # Check limit
        if len(self.rate_limits[key]) >= max_operations:
            return True

        # Add current operation
        self.rate_limits[key].append(current_time)
        return False

    def _update_metrics(self) -> None:
        """Update metrics file."""
        self.metrics["last_updated"] = datetime.utcnow().isoformat()

        try:
            with open(self.metrics_log, "w") as f:
                json.dump(self.metrics, f, indent=2)
        except Exception as e:
            logger.error(f"Failed to update metrics: {e}")

    def _get_recent_events(self, hours: int = 24) -> List[Dict[str, Any]]:
        """Get recent security events."""
        cutoff_time = datetime.utcnow().timestamp() - (hours * 3600)
        recent_events = []

        try:
            if self.security_events_log.exists():
                with open(self.security_events_log, "r") as f:
                    for line in f:
                        try:
                            record = json.loads(line.strip())
                            event_time = datetime.fromisoformat(
                                record["timestamp"]
                            ).timestamp()
                            if event_time > cutoff_time:
                                recent_events.append(record)
                        except (json.JSONDecodeError, KeyError, ValueError):
                            continue
        except Exception as e:
            logger.error(f"Error reading recent events: {e}")

        return recent_events

    def _analyze_top_concerns(
        self, events: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """Analyze top security concerns from events."""
        concern_counts = {}

        for event in events:
            event_type = event.get("event_type", "unknown")
            severity = event.get("severity", "low")

            key = f"{event_type}:{severity}"
            if key not in concern_counts:
                concern_counts[key] = {
                    "count": 0,
                    "event_type": event_type,
                    "severity": severity,
                }
            concern_counts[key]["count"] += 1

        # Sort by severity and count
        severity_order = {"critical": 4, "high": 3, "medium": 2, "low": 1}
        top_concerns = sorted(
            concern_counts.values(),
            key=lambda x: (severity_order.get(x["severity"], 0), x["count"]),
            reverse=True,
        )[:5]

        return top_concerns

    def _generate_recommendations(
        self, recent_events: List[Dict[str, Any]], agent_metrics: Dict[str, Any]
    ) -> List[str]:
        """Generate security recommendations based on analysis."""
        recommendations = []

        # Check for high violation rates
        for agent_id, metrics in agent_metrics.items():
            if metrics["violation_rate"] > 0.1:  # 10% violation rate
                recommendations.append(
                    f"Agent {agent_id} has high violation rate ({metrics['violation_rate']:.1%}) - "
                    "consider additional input validation or retraining"
                )

        # Check for critical events
        critical_events = [e for e in recent_events if e.get("severity") == "critical"]
        if critical_events:
            recommendations.append(
                f"Found {len(critical_events)} critical security events in last 24h - "
                "immediate review recommended"
            )

        # Check for repeated patterns
        event_types = [e.get("event_type") for e in recent_events]
        if event_types.count("output_scan_violation") > 5:
            recommendations.append(
                "Multiple output scan violations detected - "
                "consider strengthening output validation rules"
            )

        if not recommendations:
            recommendations.append("No immediate security concerns detected")

        return recommendations
